spring:
  config:
    activate:
      on-profile: "docker"

info:
  app:
    name: Fit Verse Docker
    description: Fitness Tracking System.
    version: 1.0.0
    profile: docker
    owner: Rupesh Dulal
    website: https://www.alfarays.tech
  build:
    timestamp: "@timestamp@"
  developer:
    name: "Rupesh Dulal"
    email: "rupeshdulal672@gmail.com"
    github: "https://github.com/rupesh-hub"
